name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

env:
  PROJECT_ID: ${{ vars.PROJECT_ID }}
  REGION: ${{ vars.REGION }}
  REPO: app-repo

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: |
          terraform apply --auto-approve \
          -var="fastapi_image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/fastapi:${{ github.event.workflow_run.head_sha }}" \
          -var="streamlit_image=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/streamlit:${{ github.event.workflow_run.head_sha }}"
        working-directory: infra
