name: CI

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: ${{ vars.PROJECT_ID}}
  REGION: ${{ vars.REGION }}
  REPO: app-repo

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push FastApi
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/fastapi:${{ github.sha }}
          docker build -t $IMAGE -f app/api/Dockerfile .
          docker push $IMAGE


      - name: Build and Push Streamlit
        run: |
          IMAGE=$REGION-docker.pkg.dev/$PROJECT_ID/$REPO/streamlit:${{ github.sha }}
          docker build -t $IMAGE -f app/streamlit/Dockerfile .
          docker push $IMAGE
